# Generated by Django 5.0.3 on 2024-04-08 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0002_remove_menu_ishot_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pay',
            field=models.BooleanField(default=False, verbose_name='PAY'),
        ),
    ]
